def data():
    users = [
        {
            'user_id':'4z6cr',
            'salt':"b'$2b$14$bjwObtQ6eROB8au4gaquLu'",
            'name':'<Example> Jim - pw:pass1',
            'password':"b'$2b$14$bjwObtQ6eROB8au4gaquLuhBljuja6D649YEtMfIfw8HAlrMGGdH2'",
            'created':'2022-06-27 06:59:59.1',
            'last_login':'2022-09-28 14:29:00.1',
        },
        {
            'user_id':'qpiqk',
            'salt':"b'$2b$14$Xt4xMz37x9NqP7d9sIUFlO'",
            'name':'<Example> Rick - pw:pass2',
            'password':"b'$2b$14$Xt4xMz37x9NqP7d9sIUFlOSFVMVDKU.GtTUW/gGbSbVAP/7vmqqlK'",
            'created':'2022-03-27 10:10:34.1',
            'last_login':'2022-10-4 15:32:03.1',
        },
        {
            'user_id':'bw8tg',
            'salt':"b'$2b$14$8uNhMbB6dmvvMg5JKzF.3u'",
            'name':'<Example> Tom - pw:pass3',
            'password':"b'$2b$14$8uNhMbB6dmvvMg5JKzF.3uWOCIJvW7XWv4JaQTgM4G1m9n7iGNgrO'",
            'created':'2022-02-11 05:12:43.1',
            'last_login':'2022-05-15 19:54:15.1',
        },
    ]

    habits = [
        {
            'user_id':'4z6cr',
            'habit_id':'6tryr',
            'title':'title_reading',
            'description':'description_good for my mind',
            'interval':'1D',
            'active':'True',
            'start_from':'',
            'difficulity':5,
            'category':'Eduction',
            'moto':'The more you learn the better',
            'importance':5,
            'style':1,
            'milestone_streak':30,
            'is_dynamic':'False',
            'checkin_num_before_deadline':0,
            'dynamic_count':0,
            'created_on':'2022-05-11 05:12:43.1',
            'prev_deadline':'2022-05-11 05:12:43.1',
            'next_deadline':'2022-05-12 05:12:43.1',
            'streak':0,
            'success':0,
            'fail':0,
            'cost':0,
            'cost_accum':0
        },
        {
            'user_id':'4z6cr',
            'habit_id':'bxmqk',
            'title':'title_laughing',
            'description':'Why not?',
            'interval':'1D',
            'active':'True',
            'start_from':'',
            'difficulity':1,
            'category':'Mental Health',
            'moto':'More joy is better',
            'importance':5,
            'style':1,
            'milestone_streak':365,
            'is_dynamic':'False',
            'checkin_num_before_deadline':0,
            'dynamic_count':0,
            'created_on':'2022-05-13 05:12:43.1',
            'prev_deadline':'2022-05-14 05:12:43.1',
            'next_deadline':'2022-05-15 05:12:43.1',
            'streak':1,
            'success':1,
            'fail':0,
            'cost':0,
            'cost_accum':0
        },
        {
            'user_id':'4z6cr',
            'habit_id':'fy2um',
            'title':'title_cinema',
            'description':'Movie night',
            'interval':'1W',
            'active':'True',
            'start_from':'',
            'difficulity':1,
            'category':'Entertainment',
            'moto':'To get inspired',
            'importance':2,
            'style':1,
            'milestone_streak':4,
            'is_dynamic':'False',
            'checkin_num_before_deadline':0,
            'dynamic_count':0,
            'created_on':'2022-06-13 05:12:43.1',
            'prev_deadline':'2022-06-13 05:12:43.1',
            'next_deadline':'2022-06-20 05:12:43.1',
            'streak':0,
            'success':1,
            'fail':0,
            'cost':4.95,
            'cost_accum':0
        },
    ]

    checkins = [
        {
            'user_id':'4z6cr',
            'habit_id':'6tryr',
            'checkin_id':'hed69',
            'checkin_datetime':'2022-05-11 05:12:43.1',
            'deadline':'2022-05-12 05:12:43.1',
            'success':'True',
            'note':'Great work',
            'rating':4,
            'cost':0,
            'cost_accum':0,
            'dynamic':'False',
            'dynamic_count':0
        },
        {
            'user_id':'4z6cr',
            'habit_id':'6tryr',
            'checkin_id':'9luhm',
            'checkin_datetime':'2022-05-11 05:12:43.1',
            'deadline':'2022-05-13 05:12:43.1',
            'success':'True',
            'note':'Wow',
            'rating':5,
            'cost':0,
            'cost_accum':0,
            'dynamic':'False',
            'dynamic_count':0
        },
        {
            'user_id':'4z6cr',
            'habit_id':'6tryr',
            'checkin_id':'cg3yacl',
            'checkin_datetime':'2022-05-13 05:12:43.1',
            'deadline':'2022-05-14 05:12:43.1',
            'success':'True',
            'note':'Amazing',
            'rating':4,
            'cost':0,
            'cost_accum':0,
            'dynamic':'False',
            'dynamic_count':0
        },
    ]

    return users, habits, checkins